name: Melle
favicon: null
layout_spectrum: 0.8606384096201509
typography_spectrum: 0.5015011201612651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.06471181870438159
  lightness: 0.3529727051500231
  saturation: 0.7713946076110005
  rhythmicContrast: 0.75945696933195
purpose: []
